apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: op-scim-tls
spec:
  secretName: op-scim-tls
  commonName: 1pscim-bridge.gladia.io
  dnsNames:
    - 1pscim-bridge.gladia.io
  issuerRef:
    name: letsencrypt-prod-traefik
    kind: ClusterIssuer